# docker-compose-application.yml

services:
  broker:
    extends:
      file: ./smart-garden-infra/docker-compose.yml
      service: broker
    networks:
      - custom_network

  influxdb:
    extends:
      file: ./smart-garden-infra/docker-compose.yml
      service: influxdb
    networks:
      - custom_network

  redis:
    extends:
      file: ./smart-garden-infra/docker-compose.yml
      service: redis
    networks:
      - custom_network

  db:
    extends:
      file: ./smart-garden-infra/docker-compose.yml
      service: db
    networks:
      - custom_network

  app:
    build: ./django_image/
    container_name: django_app
    volumes:
      - ./app:/src
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - broker
    command: daphne -b 0.0.0.0 -p 8000 core.asgi:application
    networks:
      - custom_network

  # celery:
  #   build: ./django_image/
  #   container_name: celery_worker
  #   volumes:
  #     - ./app:/src
  #   env_file:
  #     - .env
  #   environment:
  #     - C_FORCE_ROOT=true
  #   depends_on:
  #     - db
  #     - redis
  #     - broker
  #     - app
  #   command: celery -A core worker -l INFO --autoscale=4,8 -Q high_priority,default,low_priority
  #   networks:
  #     - custom_network

  # celery-beat:
  #   build: ./django_image/
  #   container_name: celery_beat
  #   volumes:
  #     - ./app:/src
  #   env_file:
  #     - .env
  #   depends_on:
  #     - db
  #     - redis
  #     - broker
  #     - app
  #   command: celery -A core beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
  #   networks:
  #     - custom_network

  # flower:
  #   build: ./django_image/
  #   container_name: flower
  #   volumes:
  #     - ./app:/src
  #   ports:
  #     - "5555:5555"
  #   env_file:
  #     - .env
  #   environment:
  #     - FLOWER_BASIC_AUTH=${FLOWER_USER:-admin}:${FLOWER_PASSWORD:-admin123}
  #   depends_on:
  #     - db
  #     - redis
  #     - broker
  #     - celery
  #   command: celery -A core flower --port=5555 --broker_api=http://guest:guest@broker:15672/api/
  #   networks:
  #     - custom_network

  nginx:
    extends:
      file: ./smart-garden-infra/docker-compose.yml
      service: nginx
    volumes:
      - ./smart-garden-infra/nginx_image:/etc/nginx/conf.d
      - ./smart-garden-front/out:/var/www/html
    networks:
      - custom_network
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=haj-ebram.ir
      - NGINX_PORT=80


networks:
  custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24

volumes:
  mysql_data: