# version: "3"

services:
  broker:
    image: registry-git.digikala.com/digi-automation/server-codes/ci-cd-boilerplate/rabbitmq:3.12C
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
      - 15692:15692
      - 6000:1883
    volumes:
      - "./rbmq_image/conf/:/etc/rabbitmq/"
    
  redis:
    image: registry-git.digikala.com/digi-automation/server-codes/ci-cd-boilerplate/redis:alpine
    container_name: redis_db
    ports:
      - 6379:6379

  nginx:
    image: registry-git.digikala.com/digi-automation/server-codes/ci-cd-boilerplate/nginx
    container_name: nginx
    volumes:
      - ./nginx_image:/etc/nginx/conf.d
    ports:
      - "6001:6001"
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=6001

  db:
    image: registry-git.digikala.com/digi-automation/server-codes/ci-cd-boilerplate/mysql:latest
    container_name: mysql_db
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./data/db:/var/lib/mysql
      - ./mysql_image:/docker-entrypoint-initdb.d
    environment:
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "root"

  influxdb:
    image: registry-git.digikala.com/digi-automation/server-codes/ci-cd-boilerplate/influxdb:2.7.6
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb_data:/var/lib/influxdb2
    environment:
      - INFLUXDB_DB=mydb
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin  
