# Generated by Django 5.0.6 on 2025-02-22 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TRFParam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param_name', models.CharField(max_length=255)),
                ('param_id', models.PositiveIntegerField(default='1', null=True)),
                ('is_advance', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TRFProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_version', models.CharField(default='V.1', max_length=36)),
                ('sensor_task_id', models.CharField(max_length=36)),
            ],
        ),
        migrations.RemoveField(
            model_name='generalerror',
            name='pigeon',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='live_access',
        ),
        migrations.CreateModel(
            name='SensorPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(default='def', max_length=255)),
                ('section', models.CharField(default='def', max_length=255)),
                ('pin_num', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='nd.trfparam')),
            ],
        ),
        migrations.CreateModel(
            name='TRFUserConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=255)),
                ('parameter_id', models.CharField(max_length=255)),
                ('command_type', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
