# Generated by Django 5.0.6 on 2025-02-22 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nd', '0002_trfparam_trfproject_remove_generalerror_pigeon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trfparam',
            name='default_value',
            field=models.CharField(default='1', max_length=255),
        ),
        migrations.AddField(
            model_name='trfparam',
            name='detail',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='trfparam',
            name='is_settable',
            field=models.BooleanField(default=True),
        ),
    ]
