# Generated by Django 5.0.6 on 2025-02-26 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nd', '0003_trfparam_default_value_trfparam_detail_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrole',
            old_name='advance_controll',
            new_name='advance_control',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='nd.userrole'),
        ),
        migrations.AlterField(
            model_name='trfparam',
            name='param_id',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
    ]
