# Generated by Django 5.0.6 on 2025-02-26 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nd', '0004_rename_advance_controll_userrole_advance_control_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='user_role',
        ),
        migrations.AddField(
            model_name='customuser',
            name='access_level',
            field=models.IntegerField(choices=[(0, 'Viewer'), (1, 'Operator'), (2, 'Developer'), (3, 'Maintainer')], default=0),
        ),
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
