# Generated by Django 5.0.1 on 2025-05-19 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0002_power_powerconsumption_pump_schedule_systemlog_valve_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='plants',
        ),
        migrations.RemoveField(
            model_name='reading',
            name='sensor',
        ),
        migrations.DeleteModel(
            name='GardenSection',
        ),
        migrations.DeleteModel(
            name='Plant',
        ),
        migrations.DeleteModel(
            name='Reading',
        ),
        migrations.DeleteModel(
            name='Sensor',
        ),
    ]
