# Generated by Django 5.0.1 on 2025-05-20 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0003_remove_sensor_plants_remove_reading_sensor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Garden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='valve',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='power',
            name='garden',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='power_records', to='garden.garden'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='powerconsumption',
            name='garden',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='power_consumptions', to='garden.garden'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pump',
            name='garden',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='pumps', to='garden.garden'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='garden',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='garden.garden'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='systemlog',
            name='garden',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='system_logs', to='garden.garden'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='valve',
            name='garden',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='valves', to='garden.garden'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='waterusage',
            name='garden',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='water_usages', to='garden.garden'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='valve',
            unique_together={('garden', 'number')},
        ),
        migrations.CreateModel(
            name='GardenAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('staff', 'Staff')], default='staff', max_length=10)),
                ('garden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_accesses', to='garden.garden')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garden_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Garden Accesses',
                'unique_together': {('user', 'garden')},
            },
        ),
    ]
