"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta

# =====================================
# =====related to load react app======
# =====================================
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
FRONTEND_DIR = os.path.join(BASE_DIR, 'front/build')
STATICS_DIR = os.path.join(BASE_DIR, 'front/build/static')
OTA_DIR = os.path.join(BASE_DIR, 'OTA/')
STATICFILES_DIRS = [
    FRONTEND_DIR, STATICS_DIR,OTA_DIR
]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'trf/static/'
# =====================================

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-tvn+v@r%^nzm@be-24u4xbv4cge-ufd@swj@g(u71htat=+1_y'
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
ALLOWED_HOSTS = ['*']

# Application definition
INSTALLED_APPS = [
    # for handling websoc
    'daphne',
    'nd',
    'django.contrib.auth',
    "rest_framework",
    # for swagger
    'drf_spectacular',
    # for authentication
    "djoser",
    # django default
    'django.contrib.admin',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    # for handle static file of react
    'django.contrib.staticfiles',
    # for handle talk to front
    'corsheaders',
    # for handling get data from celery worker
    'django_celery_results',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
]

# ===================================================
# ===========related to load react local=============
# ===================================================
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    f"http://{os.environ['LOCAL_IP']}:5001",  
    "https://robotics.digikala.com"
]

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

CSRF_TRUSTED_ORIGINS = ["https://robotics.digikala.com", "http://localhost"]
# ===================================================


# ===================================================
# ========related to load authentication=============
# ===================================================
REST_FRAMEWORK = {
    'COERCE_DECIMAL_TO_STRING': False,
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',

}

DJOSER = {
    'SERIALIZERS': {
        'user': 'nd.serializers.CustomUserSerializer',
        'current_user': 'nd.serializers.CustomUserSerializer',
    },
    'DISABLE_ENDPOINTS': [
        'users', 'users/confirm', 'users/resend_activation',
        'users/set_password', 'users/reset_password', 'users/set_username',
        'users/reset_username', 'users/reset_username_confirm', 'token/login', 'token/logout'
    ],
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=1),
    'AUTH_HEADER_TYPES': ('JWT',),
}
REST_USE_JWT = True

AUTH_USER_MODEL = 'nd.CustomUser'
# ===================================================

SPECTACULAR_SETTINGS = {
    'TITLE': 'ND API',
    'DESCRIPTION': 'API documentations',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'EXCLUDE_PATHS': [
        '/auth/users/',
        '/auth/users/confirm/',
        '/auth/users/resend_activation/',
        '/auth/users/set_password/',
        '/auth/users/reset_password/',
        '/auth/users/set_username/',
        '/auth/users/reset_username/',
        '/auth/users/reset_username_confirm/',
        '/auth/token/login/',
        '/auth/token/logout/',
        '/auth/users/activation/',
        
    ],
}
# ====================================

ROOT_URLCONF = 'core.urls'
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS':  [FRONTEND_DIR, STATICS_DIR],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'

ASGI_APPLICATION = "core.asgi.application"

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'trf_app_db',
        'USER': 'root',
        'PASSWORD': 'root',
        'HOST': os.environ['LOCAL_IP'],
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    # {
    #     'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    # },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Tehran'

USE_I18N = True
USE_TZ = True


# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# for handling https
# SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# for handling logs
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'DEBUG',  # You can set this to 'DEBUG', 'INFO', 'WARNING', 'ERROR', or 'CRITICAL'
    },
}

# for handling channels
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [(os.environ['LOCAL_IP'], 6379)],
        },
    },
}

# Celery Configuration Options
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/Tehran'
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 60 * 60 * 24 * 7
CELERY_BROKER_URL = f"amqp://celery:celery@{os.environ['LOCAL_IP']}:5672/wvh"
# CELERY_RESULT_BACKEND = 'rpc://'

CELERY_RESULT_BACKEND = 'django-db'
CELERY_CACHE_BACKEND = 'django-cache'
CELERY_RESULT_EXTENDED = True
